version: '3.8'

services:
  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: examplepassword
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - django-network

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    environment:
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: examplepassword
    depends_on:
      - db
    networks:
      - django-network

networks:
  django-network:

volumes:
  postgres-data:
