version: '3.8'

services:
  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: examplepassword
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - nextjs-network

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: sh -c "npx prisma db push && npm run start"
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: 'postgresql://postgres:examplepassword@db:5432/postgres?schema=public'
    depends_on:
      - db
    networks:
      - nextjs-network

networks:
  nextjs-network:

volumes:
  postgres-data:
